version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: DockerFile.prod
    container_name: nextjs-frontend-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    command: npm run start
